### ISSUE TITLE
Not able to create shared memory segment for PID

### ISSUE THREAD

**Issue by seyfer** [kriswallsmith/spork#32]
Some times it happens..

```
PHP Fatal error:  Uncaught exception 'Spork\Exception\ProcessControlException' with message 'Not able to create shared memory segment for PID: 20786' in /var/www/link.ru/vendor/kriswallsmith/spork/src/Spork/SharedMemory.php:91
Stack trace:
#0 /var/www/link.ru/vendor/kriswallsmith/spork/src/Spork/ProcessManager.php(119): Spork\SharedMemory->send(Object(Spork\Util\ExitMessage), false)
#1 [internal function]: Spork\ProcessManager->Spork\{closure}()
#2 {main}
  thrown in /var/www/link.ru/vendor/kriswallsmith/spork/src/Spork/SharedMemory.php on line 91
PHP Fatal error:  Uncaught exception 'Spork\Exception\ProcessControlException' with message 'Not able to create shared memory segment for PID: 20786' in /var/www/link.ru/vendor/kriswallsmith/spork/src/Spork/SharedMemory.php:91
Stack trace:
#0 /var/www/link.ru/vendor/kriswallsmith/spork/src/Spork/ProcessManager.php(119): Spork\SharedMemory->send(Object(Spork\Util\ExitMessage), false)
#1 [internal function]: Spork\ProcessManager->Spork\{closure}()
#2 {main}
  thrown in /var/www/link.ru/vendor/kriswallsmith/spork/src/Spork/SharedMemory.php on line 91
```

Related to this update
https://github.com/kriswallsmith/spork/pull/28

**Comment by iwiznia** [comment]
I'm getting this all the time. Any idea on what's causing this? I see shmop is enabled in phpinfo.

**Comment by TheLevti** [comment]
Might be related. Fixed similar shared memory errors on my fork.

https://github.com/TheLevti/spork/issues/7
https://github.com/TheLevti/spork/issues/9
