### ISSUE TITLE
Problems on Symfony 5.0

### ISSUE THREAD

**Issue by svaningelgem** [kriswallsmith/spork#44]
I just did a composer update and got the following messages:
```
  - Updating symfony/event-dispatcher (v4.2.1 => v5.0.7): Downloading (100%)
```

Nothing special, just a major version update, but it seems something changed under the hood:
```
TypeError: Argument 1 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an object, string given, called in <my project>/vendor/kriswallsmith/spork/src/Spork/ProcessManager.php on line 94 and defined in <my project>/vendor/symfony/event-dispatcher/EventDispatcher.php:48
Stack trace:
#0 <my project>/vendor/kriswallsmith/spork/src/Spork/ProcessManager.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('spork.pre_fork')
#1 <my project>/class.php(268): Spork\ProcessManager->fork(Array)
#2 <my project>/download.php(7): class_Downloader->start()
#3 {main}[2020-04-05 08:34:17] !! Exception encountered:

TypeError: Argument 1 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an object, string given, called in <my project>/vendor/kriswallsmith/spork/src/Spork/ProcessManager.php on line 94 and defined in <my project>/vendor/symfony/event-dispatcher/EventDispatcher.php:48
Stack trace:
#0 <my project>/vendor/kriswallsmith/spork/src/Spork/ProcessManager.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('spork.pre_fork')
#1 <my project>/class.php(268): Spork\ProcessManager->fork(Array)
#2 <my project>/download.php(7): class_Downloader->start()
#3 {main}
```

**Comment by svaningelgem** [comment]
BTW, how I solved it is via:
```
composer require symfony/event-dispatcher ^4
```
That will limit event-dispatcher to the major version 4.

**Comment by TheLevti** [comment]
Check https://github.com/TheLevti/phpfork. Its a fork of this repo where I try to keep it up to date. Its still work in progress and hopefully I can provide a pull request back into this one.
